
TARGETS = Rel.vo \
          Casts.vo \
          syn.vo \
          units.vo \
          geometry.vo \
          geometryext.vo \
          sem.vo \
          equivalence.vo \
          model.vo \
          cuberoot.vo \
          unitsext.vo \
